version: 2

# CircleCI doesn't handle large file sets properly for local builds
# https://github.com/CircleCI-Public/circleci-cli/issues/281#issuecomment-472808051
localCheckout: &localCheckout
  run: |-
    PROJECT_PATH=$(cd ${CIRCLE_WORKING_DIRECTORY}; pwd)
    mkdir -p ${PROJECT_PATH}
    cd /tmp/_circleci_local_build_repo
    git ls-files -z | xargs -0 -s 2090860 tar -c | tar -x -C ${PROJECT_PATH} 
    cp -a /tmp/_circleci_local_build_repo/.git ${PROJECT_PATH}

.openssl_job: &openssljob
  docker:
    - image: ${IMAGE}
  steps:
    - checkout # change this from "checkout" to "*localCheckout" when running CircleCI locally
    - run:
        name: Clone liboqs
        command: cd oqs_test && scripts/clone_liboqs.sh
    - run:
        name: Build liboqs
        command: cd oqs_test && scripts/build_liboqs.sh
    - run:
        name: Build OpenSSL
        command: cd oqs_test && scripts/build_openssl.sh
    - run:
        name: Run unit tests
        command: cd oqs_test && mkdir -p test-results && LD_LIBRARY_PATH=$(dirname $PWD) python3 -m nose --rednose --verbose --with-xunit --xunit-file=test-results/nosetests.xml
    - store_test_results: # Note that this command will fail when running CircleCI locally, that is expected behaviour
        path: oqs_test/test-results

jobs:
  debian-buster-amd64:
    <<: *openssljob
    environment:
      IMAGE: dstebila/liboqs:debian-buster-amd64-0.1.0
      ARCH: x64
      LIBOQS: master
      OPENSSL: 111
  ubuntu-xenial-x86_64:
    <<: *openssljob
    environment:
      IMAGE: dstebila/liboqs:ubuntu-xenial-x86_64-0.1.0
      ARCH: x64
      LIBOQS: master
      OPENSSL: 111
  ubuntu-xenial-x86_64-shared:
    <<: *openssljob
    environment:
      IMAGE: dstebila/liboqs:ubuntu-xenial-x86_64-0.1.0
      ARCH: x64
      LIBOQS: master
      OPENSSL: 111
      LIBTYPE: shared

workflows:
  version: 2
  build:
    jobs:
      - debian-buster-amd64
      - ubuntu-xenial-x86_64
      - ubuntu-xenial-x86_64-shared
  #nightly:
  #  triggers:
  #    - schedule:
  #        cron: "0 3 * * *"
  #        filters:
  #          branches:
  #          only:
  #             - OQS-OpenSSL_1_1_1-stable
    jobs:
      - debian-buster-amd64
      - ubuntu-xenial-x86_64
      - ubuntu-xenial-x86_64-shared
